[package]
name = "evry"
version = "0.1.0"
authors = ["Sean Breckenridge <seanbrecke@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
app_dirs = "^1.2.1"
pest = "2.0"
pest_derive = "2.0"
